### ISSUE TITLE
Possible edge case with multiple bridges in hue-register command

### ISSUE THREAD

**Issue by mickdekkers** [PsychoLlama/hue-connect#2]
Hey, I was looking through the code of this project and I came across a possible issue.

This line causes the register callback to call itself until the link button is pressed, but it does not account for multiple bridges. https://github.com/PsychoLlama/hue-connect/blob/master/src/bin/hue-register.js#L35

As far as I can tell, `search.cancel` just prevents callbacks from being spawned for newly found bridges, it does not break the loop in existing callbacks. This means that even if another callback has already linked to a bridge, the process will keep running until it's linked to _all_ the bridges it discovered.

The same issue affects the [code in the readme](https://github.com/PsychoLlama/hue-connect#discovery-1).

A simple fix would be to call `process.exit` after `search.cancel`, but if you wanna get fancy you can probably implement something with [cancelable promises](https://github.com/sindresorhus/p-cancelable) or [futures](https://github.com/fluture-js/Fluture), which can also be canceled.

**Comment by PsychoLlama** [comment]
You're right, thanks! I've only ever tested it on one bridge, but I've got another older model I can try it against.

Good eye 👌

**Comment by mickdekkers** [comment]
10/10 would 👀 again 👌

**Comment by PsychoLlama** [comment]
Fixed in `v0.2.1` :tada:
